.TH "debug.cpp" 3 "6 Jul 2010" "GPU_simulations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'debug.h'\fP
.br
\fC#include 'assert.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdebug_getverbosity\fP ()"
.br
.RI "\fIdefault is 1 \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fB_debug_verbosity\fP = 1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int debug_getverbosity ()"
.PP
default is 1 
.SH "Variable Documentation"
.PP 
.SS "int \fB_debug_verbosity\fP = 1"
.SH "Author"
.PP 
Generated automatically by Doxygen for GPU_simulations from the source code.
