.TH "gpu_anal.h" 3 "6 Jul 2010" "GPU_simulations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gpu_anal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'param.h'\fP
.br
\fC#include 'gputil.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgpuanalfw\fP"
.br
.ti -1c
.RI "struct \fBgpuanalpc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgpu_anal_fw_step\fP (\fBgpuanalfw\fP *anal_fw, \fBtensor\fP *m, \fBtensor\fP *h, double *totalTime)"
.br
.ti -1c
.RI "__global__ void \fB_gpu_anal_fw_step\fP (float *mx, float *my, float *mz, float *hx, float *hy, float *hz, float dt, float alpha)"
.br
.ti -1c
.RI "\fBgpuanalfw\fP * \fBnew_gpuanalfw\fP (\fBparam\fP *p)"
.br
.ti -1c
.RI "\fBgpuanalfw\fP * \fBnew_gpuanalpc\fP (\fBparam\fP *p)"
.br
.ti -1c
.RI "void \fBgpu_anal_fw_step_unsafe\fP (float *m, float *h, float dt, float alpha, int N)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file implements the forward and predictor/corrector semi-analytical time stepping scheme for solving the LL equation.
.PP
\fBAuthor:\fP
.RS 4
Ben Van de Wiele 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "__global__ void _gpu_anal_fw_step (float * mx, float * my, float * mz, float * hx, float * hy, float * hz, float dt, float alpha)"
.SS "void gpu_anal_fw_step (\fBgpuanalfw\fP * anal_fw, \fBtensor\fP * m, \fBtensor\fP * h, double * totalTime)"
.SS "void gpu_anal_fw_step_unsafe (float * m, float * h, float dt, float alpha, int N)"
.SS "\fBgpuanalfw\fP* new_gpuanalfw (\fBparam\fP * p)"
.SS "\fBgpuanalfw\fP* new_gpuanalpc (\fBparam\fP * p)"
.SH "Author"
.PP 
Generated automatically by Doxygen for GPU_simulations from the source code.
