.TH "gpuc2cplan" 3 "6 Jul 2010" "GPU_simulations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gpuc2cplan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gpuconv1.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "cufftHandle \fBhandle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A complex-to-complex FFT plan on the GPU. 
.PP
\fBSee also:\fP
.RS 4
\fBnew_gpuc2cplan()\fP, \fBdelete_gpuc2cplan()\fP, \fBgpuc2cplan_exec()\fP. 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "cufftHandle \fBgpuc2cplan::handle\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GPU_simulations from the source code.
