.TH "gpupad.h" 3 "6 Jul 2010" "GPU_simulations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gpupad.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tensor.h'\fP
.br
\fC#include 'gputil.h'\fP
.br
\fC#include 'assert.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgpu_copy_pad\fP (\fBtensor\fP *source, \fBtensor\fP *dest)"
.br
.ti -1c
.RI "void \fBgpu_copy_unpad\fP (\fBtensor\fP *source, \fBtensor\fP *dest)"
.br
.ti -1c
.RI "void \fBgpu_copy_pad_unsafe\fP (float *source, float *dest, int S0, int S1, int S2, int D0, int D1, int D2)"
.br
.RI "\fIdest size \fP"
.ti -1c
.RI "void \fBgpu_copy_unpad_unsafe\fP (float *source, float *dest, int S0, int S1, int S2, int D0, int D1, int D2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Central location for all copy-pad functions (copying blocks of data between 3D arrays with different sizes)
.PP
\fBAuthor:\fP
.RS 4
Arne Vansteenkiste 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void gpu_copy_pad (\fBtensor\fP * source, \fBtensor\fP * dest)".PP
\fBFor internal use only.\fP
.RS 4
.RE
.PP

.SS "void gpu_copy_pad_unsafe (float * source, float * dest, int S0, int S1, int S2, int D0, int D1, int D2)"
.PP
dest size \fBParameters:\fP
.RS 4
\fIS2\fP source size 
.RE
.PP

.SS "void gpu_copy_unpad (\fBtensor\fP * source, \fBtensor\fP * dest)".PP
\fBFor internal use only.\fP
.RS 4
.RE
.PP

.SS "void gpu_copy_unpad_unsafe (float * source, float * dest, int S0, int S1, int S2, int D0, int D1, int D2)"
.SH "Author"
.PP 
Generated automatically by Doxygen for GPU_simulations from the source code.
