.TH "gputil_test.cpp" 3 "6 Jul 2010" "GPU_simulations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gputil_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'timer.h'\fP
.br
\fC#include 'gputil.h'\fP
.br
\fC#include 'gpuconv2.h'\fP
.br
\fC#include 'tensor.h'\fP
.br
\fC#include 'assert.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmakeconf_test\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests for gputil
.PP
\fBAuthor:\fP
.RS 4
Arne Vansteenkiste 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.SS "void makeconf_test ()"
.SH "Author"
.PP 
Generated automatically by Doxygen for GPU_simulations from the source code.
