.TH "main-ben.h" 3 "6 Jul 2010" "GPU_simulations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main-ben.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gputil.h'\fP
.br
\fC#include 'kernel.h'\fP
.br
\fC#include 'assert.h'\fP
.br
\fC#include 'timer.h'\fP
.br
\fC#include 'timestep.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SH "Detailed Description"
.PP 
This file contains the functions required to run a complete simulation.
.PP
\fBAuthor:\fP
.RS 4
Ben Van de Wiele 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for GPU_simulations from the source code.
