.TH "main-ben.cpp" 3 "6 Jul 2010" "GPU_simulations" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main-ben.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main-ben.h'\fP
.br
\fC#include 'gputil.h'\fP
.br
\fC#include 'kernel.h'\fP
.br
\fC#include 'assert.h'\fP
.br
\fC#include 'timer.h'\fP
.br
\fC#include 'timestep.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBparam\fP * \fBread_param\fP ()"
.br
.ti -1c
.RI "void \fBinitialize_m\fP (\fBtensor\fP *, \fBparam\fP *)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void initialize_m (\fBtensor\fP * m, \fBparam\fP * p)"
.SS "int main (int argc, char ** argv)"
.SS "\fBparam\fP* read_param ()"
.SH "Author"
.PP 
Generated automatically by Doxygen for GPU_simulations from the source code.
