.PHONY: clean

all:
	cp /usr/local/cuda/lib64/libcudart.so ./libcudart.so.3
	cp /usr/local/cuda/lib64/libcufft.so ./libcufft.so.3
	cp /usr/local/cuda/lib64/libcurand.so ./libcurand.so.3
	
clean:
	rm -rf fftw/* *.so *.a libcudart.* libcufft.* mumax.pyc
