.PHONY: clean

all:
	cp /usr/local/cuda/lib64/libcudart.so .
	cp /usr/local/cuda/lib64/libcufft.so .
	cp /usr/local/cuda/lib64/libcurand.so .
	
clean:
	rm -rf fftw/* *.so *.a libcudart.* libcufft.* mumax.pyc
