include $(GOROOT)/src/Make.$(GOARCH)

TARG=tensor
GOFILES=\
	arrayslice.go\
	iterator.go\
	io.go\
	tensor.go\
	vector.go\
	block.go\
	storedtensor.go\
	vectorblock.go\

include $(GOROOT)/src/Make.pkg
